//! Lock file generation and parsing for reproducible builds.

use serde::{Deserialize, Serialize};
use std::path::Path;

/// Represents a lumen.lock file for reproducible dependency resolution.
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct LockFile {
    /// All resolved packages with exact versions
    pub package: Vec<LockedPackage>,
}

/// A single locked package with exact version and source.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, Hash)]
pub struct LockedPackage {
    /// Package name
    pub name: String,
    /// Exact version (not a range)
    pub version: String,
    /// Package source (registry URL or path)
    pub source: String,
    /// SHA-256 checksum (for registry packages only)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    /// Direct dependencies (name + version strings)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl LockFile {
    /// Load a lock file from disk.
    pub fn load(path: &Path) -> Result<Self, String> {
        if !path.exists() {
            return Ok(Self::default());
        }

        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("cannot read lock file: {}", e))?;

        toml::from_str(&content)
            .map_err(|e| format!("invalid lock file: {}", e))
    }

    /// Save the lock file to disk.
    pub fn save(&self, path: &Path) -> Result<(), String> {
        let header = "# This file is automatically generated by lumen pkg.\n# Do not edit manually.\n\n";

        let content = toml::to_string_pretty(&self)
            .map_err(|e| format!("failed to serialize lock file: {}", e))?;

        let full_content = format!("{}{}", header, content);

        std::fs::write(path, &full_content)
            .map_err(|e| format!("cannot write lock file: {}", e))
    }

    /// Add or update a locked package.
    pub fn add_package(&mut self, pkg: LockedPackage) {
        let mut pkg = pkg;
        if pkg.is_path_dependency() {
            if let Some(path) = pkg.get_path().map(str::to_owned) {
                // Keep path sources consistently encoded as `path+<relative-path>`.
                pkg.source = format!("path+{}", path);
            }
        }

        // Remove existing entry with same name
        if self.get_package(&pkg.name).is_some() {
            self.package.retain(|p| p.name != pkg.name);
        }
        self.package.push(pkg);
    }

    /// Get a package by name.
    pub fn get_package(&self, name: &str) -> Option<&LockedPackage> {
        self.package.iter().find(|p| p.name == name)
    }

}

impl LockedPackage {
    /// Create a new locked package for a path dependency.
    pub fn from_path(name: String, path: String) -> Self {
        Self {
            name,
            version: "0.1.0".to_string(), // Path deps use version from their lumen.toml
            source: format!("path+{}", path),
            checksum: None,
            dependencies: Vec::new(),
        }
    }

    /// Create a new locked package for a registry dependency.
    #[allow(dead_code)]
    pub fn from_registry(
        name: String,
        version: String,
        registry_url: String,
        checksum: String,
    ) -> Self {
        Self {
            name,
            version,
            source: format!("registry+{}", registry_url),
            checksum: Some(checksum),
            dependencies: Vec::new(),
        }
    }

    /// Check if this is a path dependency.
    pub fn is_path_dependency(&self) -> bool {
        self.source.starts_with("path+")
    }

    /// Get the path for a path dependency.
    pub fn get_path(&self) -> Option<&str> {
        self.source.strip_prefix("path+")
    }

    /// Get the registry URL for a registry dependency.
    #[allow(dead_code)]
    pub fn get_registry_url(&self) -> Option<&str> {
        self.source.strip_prefix("registry+")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lock_file_round_trip() {
        let mut lock = LockFile::default();

        lock.add_package(LockedPackage {
            name: "http-utils".to_string(),
            version: "1.2.0".to_string(),
            source: "registry+https://registry.lumen-lang.org".to_string(),
            checksum: Some("sha256:abc123".to_string()),
            dependencies: vec!["json-parser 0.3.2".to_string()],
        });

        lock.add_package(LockedPackage {
            name: "mathlib".to_string(),
            version: "0.1.0".to_string(),
            source: "path+../mathlib".to_string(),
            checksum: None,
            dependencies: vec![],
        });

        let toml = toml::to_string_pretty(&lock).unwrap();
        let parsed: LockFile = toml::from_str(&toml).unwrap();

        assert_eq!(parsed.package.len(), 2);
        assert_eq!(parsed.get_package("http-utils").unwrap().version, "1.2.0");
        assert_eq!(parsed.get_package("mathlib").unwrap().version, "0.1.0");
    }

    #[test]
    fn locked_package_path_dependency() {
        let pkg = LockedPackage::from_path("mathlib".to_string(), "../mathlib".to_string());
        assert!(pkg.is_path_dependency());
        assert_eq!(pkg.get_path(), Some("../mathlib"));
        assert_eq!(pkg.get_registry_url(), None);
    }

    #[test]
    fn locked_package_registry_dependency() {
        let pkg = LockedPackage::from_registry(
            "http-utils".to_string(),
            "1.2.0".to_string(),
            "https://registry.lumen-lang.org".to_string(),
            "sha256:abc123".to_string(),
        );
        assert!(!pkg.is_path_dependency());
        assert_eq!(pkg.get_path(), None);
        assert_eq!(
            pkg.get_registry_url(),
            Some("https://registry.lumen-lang.org")
        );
    }

    #[test]
    fn add_package_replaces_existing() {
        let mut lock = LockFile::default();

        lock.add_package(LockedPackage::from_path("pkg".to_string(), "../pkg".to_string()));
        assert_eq!(lock.package.len(), 1);

        lock.add_package(LockedPackage::from_path("pkg".to_string(), "../pkg2".to_string()));
        assert_eq!(lock.package.len(), 1);
        assert_eq!(lock.get_package("pkg").unwrap().get_path(), Some("../pkg2"));
    }
}
