//! Generated Stencil Constants (Placeholder)
//!
//! This file is auto-generated by build.rs. DO NOT EDIT BY HAND.
//!
//! Stencil extraction is not supported on this platform or failed during build.
//! All stencils are empty placeholders.

#![allow(dead_code)]

/// Placeholder: stencil extraction not supported on this platform
pub const STENCIL_ADD: &[u8] = &[];
pub const STENCIL_ADD_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_SUB: &[u8] = &[];
pub const STENCIL_SUB_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_MUL: &[u8] = &[];
pub const STENCIL_MUL_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_DIV: &[u8] = &[];
pub const STENCIL_DIV_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_LOADK: &[u8] = &[];
pub const STENCIL_LOADK_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_MOVE: &[u8] = &[];
pub const STENCIL_MOVE_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_JMP: &[u8] = &[];
pub const STENCIL_JMP_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_TEST: &[u8] = &[];
pub const STENCIL_TEST_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_RETURN: &[u8] = &[];
pub const STENCIL_RETURN_HOLES: &[(usize, &str)] = &[];

pub const STENCIL_CALL: &[u8] = &[];
pub const STENCIL_CALL_HOLES: &[(usize, &str)] = &[];

/// No stencils available on this platform
pub const AVAILABLE_STENCILS: &[&str] = &[];
