/// Map a string name to an IntrinsicId, if it corresponds to a built-in function.
fn get_intrinsic_id(name: &str) -> Option<IntrinsicId> {
    match name {
        // "print" and "format" are variadic and should be lowered as Calls
        // to call_builtin instead of Intrinsic opcodes.
        "len" | "length" => Some(IntrinsicId::Length),
        "range" => Some(IntrinsicId::Range),
        "string" => Some(IntrinsicId::ToString),
        "int" => Some(IntrinsicId::ToInt),
        "float" => Some(IntrinsicId::ToFloat),
        "type" | "type_of" => Some(IntrinsicId::TypeOf),
        "keys" => Some(IntrinsicId::Keys),
        "values" => Some(IntrinsicId::Values),
        "join" => Some(IntrinsicId::Join),
        "split" => Some(IntrinsicId::Split),
        "append" => Some(IntrinsicId::Append),
        "contains" | "has" => Some(IntrinsicId::Contains),
        "slice" => Some(IntrinsicId::Slice),
        "min" => Some(IntrinsicId::Min),
        "max" => Some(IntrinsicId::Max),
        "confirm" | "matches" => Some(IntrinsicId::Matches),
        "trace_ref" => Some(IntrinsicId::TraceRef),
        "abs" => Some(IntrinsicId::Abs),
        // Collection operations
        "sort" => Some(IntrinsicId::Sort),
        "reverse" => Some(IntrinsicId::Reverse),
        "map" => Some(IntrinsicId::Map),
        "filter" => Some(IntrinsicId::Filter),
        "reduce" => Some(IntrinsicId::Reduce),
        "flat_map" => Some(IntrinsicId::FlatMap),
        "zip" => Some(IntrinsicId::Zip),
        "enumerate" => Some(IntrinsicId::Enumerate),
        "any" => Some(IntrinsicId::Any),
        "all" => Some(IntrinsicId::All),
        "find" => Some(IntrinsicId::Find),
        "position" => Some(IntrinsicId::Position),
        "group_by" => Some(IntrinsicId::GroupBy),
        "chunk" => Some(IntrinsicId::Chunk),
        "window" => Some(IntrinsicId::Window),
        "flatten" => Some(IntrinsicId::Flatten),
        "unique" => Some(IntrinsicId::Unique),
        "take" => Some(IntrinsicId::Take),
        "drop" => Some(IntrinsicId::Drop),
        "first" => Some(IntrinsicId::First),
        "last" => Some(IntrinsicId::Last),
        "is_empty" => Some(IntrinsicId::IsEmpty),
        // String operations
        "chars" => Some(IntrinsicId::Chars),
        "starts_with" => Some(IntrinsicId::StartsWith),
        "ends_with" => Some(IntrinsicId::EndsWith),
        "index_of" => Some(IntrinsicId::IndexOf),
        "pad_left" => Some(IntrinsicId::PadLeft),
        "pad_right" => Some(IntrinsicId::PadRight),
        "trim" => Some(IntrinsicId::Trim),
        "upper" => Some(IntrinsicId::Upper),
        "lower" => Some(IntrinsicId::Lower),
        "replace" => Some(IntrinsicId::Replace),
        // Math operations
        "round" => Some(IntrinsicId::Round),
        "ceil" => Some(IntrinsicId::Ceil),
        "floor" => Some(IntrinsicId::Floor),
        "sqrt" => Some(IntrinsicId::Sqrt),
        "pow" => Some(IntrinsicId::Pow),
        "log" => Some(IntrinsicId::Log),
        "sin" => Some(IntrinsicId::Sin),
        "cos" => Some(IntrinsicId::Cos),
        "tan" => Some(IntrinsicId::Tan),
        "trunc" => Some(IntrinsicId::Trunc),
        "clamp" => Some(IntrinsicId::Clamp),
        // Utility operations
        "clone" => Some(IntrinsicId::Clone),
        "sizeof" => Some(IntrinsicId::Sizeof),
        "debug" => Some(IntrinsicId::Debug),
        "count" => Some(IntrinsicId::Count),
        "hash" => Some(IntrinsicId::Hash),
        "diff" => Some(IntrinsicId::Diff),
        "patch" => Some(IntrinsicId::Patch),
        "redact" => Some(IntrinsicId::Redact),
        "validate" => Some(IntrinsicId::Validate),
        // Map/Set operations
        "has_key" => Some(IntrinsicId::HasKey),
        "merge" => Some(IntrinsicId::Merge),
        "size" => Some(IntrinsicId::Size),
        "add" => Some(IntrinsicId::Add),
        "remove" => Some(IntrinsicId::Remove),
        "entries" => Some(IntrinsicId::Entries),
        "to_set" => Some(IntrinsicId::ToSet),
        // Formatting / filesystem / process
        // "format" => Some(IntrinsicId::Format),
        "partition" => Some(IntrinsicId::Partition),
        "read_dir" => Some(IntrinsicId::ReadDir),
        "exists" => Some(IntrinsicId::Exists),
        "mkdir" => Some(IntrinsicId::Mkdir),
        "exit" => Some(IntrinsicId::Exit),
        _ => None,
    }
}
